exports.cytaty = [
  "Dziękuję wszystkim, którzy posłuchali mojego apelu i zagłosowali na Andrzeja Dudę. Mój wkład w jego zwycięstwo to aż 2,04 proc.",
  "Będzie was PiS ruchał w dupę, będzie was PiS kurwa dymał tak, jak was Platforma nie dymała.",
  "Zarzucam prezydentowi Andrzejowi Dudzie to, że oszukał mnie przekazując za pośrednictwem Adama Kwiatkowskiego używającego numeru telefonu 603068781 prośbę o poparcie w wyborach prezydenckich dzwoniąc na mój numer dwukrotnie 535288000 i obiecując, że w przypadku wygranej w ciągu 5 dni rozpozna moją prośbę o ułaskawienie w trybie prezydenckim (nie mylić z obietnicą ułaskawienia).",
  "Będzie was PiS ruchał w dupę, będzie was PiS kurwa dymał tak, jak was Platofrma nie dymała.",
  "Dobry wieczór. Coś się… coś się popsuło i nie było mnie słychać, to powtórzę jeszcze raz.",
  "Wynik wyborczy KWW Stonogi to jest jakaś porażka, ja myślę że to polskie, kurwa głupie społeczeństwo, te kurwa banda imbecyli która głosowała na tych kurwów karakanów z PiSu to jest jakieś kurwa nieporozumienie.",
  "Jeśli tyle dla was znaczy… jeśli tyle dla was znaczy, ludzie takie zaangażowanie społeczne, jak moje gdzie postawiłem moją rodzinę, moje życie prywatne, biznes, wszystko inne i dla was tylko znaczyło to pierdolone 70 czy 80 tysięcy głosów, to was powinno się jebać kurwa, tak się powinno was jebać, jak tylko was może jebać PiS.",
  "Platforma was tak nie wyruchała, jak wyrucha was PiS, kurwa.",
  "Aż was kukle kurwa będą swędziały z bólu.",
  "To jest dramat kurwa.",
  "To jest dramat, że w tym antyludzkim państwie, w tym państwie w którym media kurwa nie były w stanie powiedzieć, że Zbigniewa Stonogę zbezczeszczono, że ten człowiek ma 118 wyroków uniewinniających, że te sądowe KURWY! powtarzam sądowe KURWY! sądowe KURWY tego człowieka oskarżały bezpodstawnie i po latach uniewinniały, że to nie jest czymś wartym tego, by tego człowieka wprowadzić do parlamentu.",
  "Ta kurwa, ten mały karakan, jebany Kaczyński śmieć, zniszczy was.",
  "Sumlińskie, Kanie, Rachonie, telewizje republiki będą wam kurwa odbierały smak życia wy kurwa idioci.",
  "Narodowi, polscy idioci.",
  "Ja mam to w piździe kurwa, bo mnie stać na wszystko.",
  "Wypierdolę jeszcze dzisiaj, już bilet kupiony z Polski i będę się z was kurwa polskie frajery śmiał, żeście takie głupie są, tacy kurwa debile, którzy te kurewstwo PiSowskie wybrali.",
  "Nie na Korwina, nie na Stonogę, tylko na jakieś kurwy Petru, Żydów w dupę jebanych kurwa, na Kukizów popierdoleńców głosowali.",
  "To właśnie jest ta kurwa Polska. Przez taką kurwę Polskę, przez was kurwa chuje nic się w tym kraju nie zmieni, bo jesteście chuj warci i trzeba was jebać, ruchać i na was zarabiać, bo jesteście bandą narodowych kurwów, nieudaczników.",
  "A wam kochani, którzyście głosowali na mnie, którzyście wspomagali mnie, dziękuję. Bo to garstka Polaków, garstka Polaków, dzisiaj to jest 70 tysięcy osób, może 80.",
  "Wyłącz ten telefon, bo ci go wyłączę na amen",
  "Jebać skurwiela z metra ciętego, jebać esbeka pierdolonego. Pluć kurwie w mordę wieczorem z rana aż kurwa zdechnie zapomniana.",
  "Ale jest pan chamski.",
  "Niech pan natychmiast wyjedzie z posesji, wjechał pan na teren posesji prywatnej. Wykonując swoje czynności procesowe ma pan oboiązek stanąć tam.",
  "Zaraz będzie pan najbardziej znanym policjantem w Polsce.",
  "Proszę teraz wyjechać stąd i dalej wykonywać swoje czyn... obowiązki.",
  "Ale pana pytam jak się pan nazywa kurwa chamie proszę wyjechać stąd natychmiast!",
  "Wypierdalać za bramę raz kurwa!",
  "Nie umiesz normalnie gadać z obywatelem to wypierdalaj za bramę bo cię odholuję. Bo cię odholuję.",
  "Co ty mówisz chamie? Co ty chamie mówisz?",
  "Daj mi telefon drugi.",
  "Ma pan telefon? Dzwonimy do oficera dyżurnego kurwa kraju.",
  "Kultury w tej pierdolonej milicji, w tej straży miejskiej, w tym wszystkim.",
  "Z milicji gorzej kurwa. W milicji takie chamy nie robiły.",
  "Naucz się kultury.",
  "A teraz dzwonię do oficera dyżurnego kraju.",
  "Mam taką propozycję dla ciebie. Jeśli chcesz ale nie musisz tego robić. Ale jak policja przyjedzie i zjesz ptasie mleczko to będziesz łagodniej wyglądał. Ja na twoim miejscu bym pojadł. Bo teraz przez 2 dni nie będziesz nic jadł. Na dołku mają chujowe jedzenie.",
  "Ale proszę ze mną nie rozmawiać jak PiS'owscy z Motłochem w Polsce. Ja pani tłumaczę, że pani umorzyła śledztwo twerdząc, że pani nie widziała nagrania audio wideo bo dostarczono nieczytelny plik, to pani obowiązkiem jako prokuratora było tak długo pisać do organów który ten dowód w sprawie posiadał a żeby ten dowód pani wydał.",
  "Tak na krótko. Kiedyś to wasze skurwysyństwo prokuratorskie się skończy, kiedyś śmieć Ziobro odejdzie. Wtedy was pozamykam. Jeśli bierzesz dziewczyno i umorzysz śledztwo nie widząc nagrania wideo które jest integralną częścią dowodową którą pokazałem to jesteś nie w porządku. Ani z ciebie prokurator ani z ciebie prawnik ani z ciebie funkcjonariusz publiczny. I ja wam tej pierdolonej Łódzkiej prokuraturze pokażę kto ma rację i jak wygląda prawo. Do widzenia.",
  "Kochani Rodacy, To nie jest sukces grubasa Stonogi! To jest Wasz sukces – sukces NIEZŁOMNYCH! A ja dziś świętuję święto prawdy. Kocham Was!",
  "Chociaż tyle mojego, że społeczeństwo sobie poogląda, jak wygląda żarcie obiadów po 2 tys. za obiadek na osobę plus winko za 5 tys.",
  "Stonoga nie jest niczyją tubą, nie stoją za nim służby specjalne.",
  "Narodowi polskiemu zrobiłem przysługę…Jeżeli przez 25 lat mieliśmy do czynienia z wieloma aferami i jedyną osobą rozliczoną z punktu widzenia (…) przepisów Kodeksu karnego jest Lew Rywin – co do którego nie mam do końca pewności, czy aby na pewno był sprawcą tamtej afery – no to coś jest nie tak.",
  "Ziobro kurwo jebana, przestań mi rodzinę prześladować pedale pisowski w dupę jebany ty!"
];
